"""empty message

Revision ID: 5f9d10e285a9
Revises: 0d24b2e125af
Create Date: 2023-08-10 14:09:27.078722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9d10e285a9'
down_revision = '0d24b2e125af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sympton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('flushing_face', sa.Integer(), nullable=False),
    sa.Column('sweating', sa.Integer(), nullable=False),
    sa.Column('headache', sa.Integer(), nullable=False),
    sa.Column('dizziness', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sympton')
    # ### end Alembic commands ###
