"""empty message

Revision ID: 707c2f1b83df
Revises: fd65338f1d36
Create Date: 2023-11-05 15:20:48.014262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707c2f1b83df'
down_revision = 'fd65338f1d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imdiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imdiary')
    # ### end Alembic commands ###
