"""empty message

Revision ID: 99933ba0a787
Revises: 
Create Date: 2023-09-02 18:38:01.337052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99933ba0a787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physicalpain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shoulder', sa.Boolean(), nullable=False),
    sa.Column('elbow', sa.Boolean(), nullable=False),
    sa.Column('finger', sa.Boolean(), nullable=False),
    sa.Column('waist', sa.Boolean(), nullable=False),
    sa.Column('wrist', sa.Boolean(), nullable=False),
    sa.Column('joint', sa.Boolean(), nullable=False),
    sa.Column('knee', sa.Boolean(), nullable=False),
    sa.Column('ankle', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sympton', sa.Column('condition', sa.Integer(), nullable=False))
    op.drop_column('sympton', 'dizziness')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sympton', sa.Column('dizziness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('sympton', 'condition')
    op.drop_table('physicalpain')
    op.drop_table('diary')
    # ### end Alembic commands ###
