"""empty message

Revision ID: b354461fb094
Revises: 08302c98439f
Create Date: 2023-09-02 16:12:42.732603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b354461fb094'
down_revision = '08302c98439f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physicalpain', sa.Column('shoulder', sa.Boolean(), nullable=True))
    op.drop_column('physicalpain', 'wrist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physicalpain', sa.Column('wrist', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('physicalpain', 'shoulder')
    # ### end Alembic commands ###
