"""empty message

Revision ID: cf711e184ff9
Revises: faee32bbf6ef
Create Date: 2023-08-16 14:05:00.828920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf711e184ff9'
down_revision = 'faee32bbf6ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary', 'modify_date')
    # ### end Alembic commands ###
