"""empty message

Revision ID: fd65338f1d36
Revises: 35b8aa90e698
Create Date: 2023-10-11 15:18:16.560369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd65338f1d36'
down_revision = '35b8aa90e698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_loginid', sa.String(length=500), nullable=False))
    op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['user_loginid'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=500), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=False)
    op.drop_column('user', 'user_loginid')
    # ### end Alembic commands ###
