"""empty message

Revision ID: fe46505ff49c
Revises: cf7b5527ba21
Create Date: 2023-08-16 10:37:02.432348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe46505ff49c'
down_revision = 'cf7b5527ba21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sympton', sa.Column('condition', sa.Integer(), nullable=False))
    op.drop_column('sympton', 'dizziness')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sympton', sa.Column('dizziness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('sympton', 'condition')
    # ### end Alembic commands ###
